# Generated by Django 6.0.4 on 2026-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
