# Generated by Django 6.0.4 on 2026-04-15 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_load_cities_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimUser',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'dim_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='FactReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='cities.city')),
                ('user', models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='social.dimuser')),
            ],
            options={
                'db_table': 'fact_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='social.dimuser')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='social.dimuser')),
            ],
            options={
                'db_table': 'relationships',
                'ordering': ['-date_sent'],
                'constraints': [models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_relationship_requester_addressee'), models.CheckConstraint(condition=models.Q(('requester', models.F('addressee')), _negated=True), name='relationship_not_self')],
            },
        ),
    ]
